repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: no-commit-to-branch
    args: [--branch, main, --branch, master]

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: go-critic
    - id: go-mod-tidy
    - id: go-mod-vendor

- repo: local
  hooks:
  - id: go-vet
    name: "go-vet"
    entry: ./backend/hooks/go-vet.sh
    types: [go]
    pass_filenames: false
    language: 'script'
    description: "Runs `go vet ./...` in backend"

  - id: go-lint
    name: "go-lint"
    entry: ./backend/hooks/go-lint.sh
    types: [go]
    pass_filenames: false
    language: 'script'
    description: "Runs `golangci-lint run` in backend"

  - id: go-test
    name: "go-test"
    entry: ./backend/hooks/go-test.sh
    types: [go]
    pass_filenames: false
    language: 'script'
    description: "Runs `go test` in backend"

  - id: node-lint
    name: "node-lint"
    entry: ./.husky/pre-commit
    files: 'package.json$'
    language: 'script'
    description: "Runs frontend linting via Husky hook when package.json changes"
