apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexus-tasks.fullname" . }}-config
  labels:
    {{- include "nexus-tasks.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  IS_DEVELOPMENT: {{ .Values.config.isDevelopment | quote }}
  DEBUG: {{ .Values.config.debug | quote }}
  APP_PORT: {{ printf ":%v" .Values.backend.port | quote }}
  ALLOWED_ORIGINS: {{ .Values.config.allowedOrigins | quote }}

  # Database
  DB_DIALECT: "postgres"
  DB_HOST: {{ include "nexus-tasks.databaseHost" . | quote }}
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  DB_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  DB_QUERYSTRING: "sslmode=disable"
  MIGRATION_DIR: "database/migrations"

  # Redis / Watermill
  MQ_DIALECT: "redis"
  MQ_DEBUG: {{ .Values.config.debug | quote }}
  MQ_TRACK: "true"
  REDIS_URI: {{ printf "%s:6379" (include "nexus-tasks.redisHost" .) | quote }}
  CONSUMER_GROUP: "nexus_worker_group"
  HANDLER_NAME: "nexus_tasks_handler"
  DEAD_LETTER_QUEUE: "poison_queue"

  # Mail
  {{- if .Values.smtp.enabled }}
  MAIL_SERVER: {{ .Values.smtp.host | quote }}
  MAIL_PORT: {{ .Values.smtp.port | quote }}
  MAIL_USERNAME: {{ .Values.smtp.username | quote }}
  MAIL_FROM: {{ .Values.smtp.fromEmail | quote }}
  MAIL_FROM_NAME: {{ .Values.smtp.fromName | quote }}
  MAIL_STARTTLS: {{ .Values.smtp.startTLS | quote }}
  MAIL_SSL_TLS: {{ .Values.smtp.sslTLS | quote }}
  USE_CREDENTIALS: {{ .Values.smtp.useCredentials | quote }}
  {{- end }}

  # SQL MQ (for Dead Letter Queue fallback)
  MQ_DB_DIALECT: "postgres"
  MQ_DB_HOST: {{ include "nexus-tasks.databaseHost" . | quote }}
  MQ_DB_PORT: "5432"
  MQ_DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  MQ_DB_USERNAME: {{ .Values.postgresql.auth.username | quote }}

  # Frontend specific
  NUXT_PUBLIC_API_URL: {{ printf "%s://%s" (ternary "https" "http" (not (empty .Values.ingress.tls))) (index .Values.ingress.hosts 0).host | quote }}
  NUXT_API_URL: {{ printf "http://%s-backend:%v" .Release.Name .Values.backend.port | quote }}
