apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-tasks.fullname" . }}-secret
  labels:
    {{- include "nexus-tasks.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.config.jwtSecret | b64enc | quote }}
  {{- if .Values.smtp.enabled }}
  MAIL_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
