"""add_is_archived_to_project

Revision ID: 0b2ef443cdbc
Revises: 63984dcaf567
Create Date: 2026-02-04 18:57:20.385385

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b2ef443cdbc"
down_revision: Union[str, None] = "63984dcaf567"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("is_archived", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_archived")
    # ### end Alembic commands ###
