"""add_completed_at_to_tasks

Revision ID: 20d7157f5587
Revises: d3a17e26b514
Create Date: 2026-02-16 16:26:17.364455

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20d7157f5587"
down_revision: Union[str, None] = "d3a17e26b514"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("completed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "completed_at")
    # ### end Alembic commands ###
